-- Verify Loans table structure
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dinspire_mfdev' 
    AND TABLE_NAME = 'Loans'
ORDER BY ORDINAL_POSITION;
